<?= view('web/include/header', ['title' => $title]) ?>

<div class="min-h-screen bg-gray-50 dark:bg-[#0b1120] flex flex-col font-sans">
    <!-- Test Header -->
    <header
        class="bg-white dark:bg-[#151e32] border-b border-gray-200 dark:border-gray-700 h-16 fixed top-0 left-0 right-0 z-50 px-4 sm:px-8 flex items-center justify-between shadow-sm">
        <div class="flex items-center gap-4">
            <h1 class="text-xl font-bold text-text-main dark:text-white hidden sm:block">
                <?= strtoupper($test_type) ?> Mock Test
            </h1>
            <div class="h-6 w-px bg-gray-300 dark:bg-gray-600 hidden sm:block"></div>
            <div class="text-sm font-medium text-text-muted dark:text-gray-400">
                Section <span id="current-section-num">1</span> of <span id="total-sections">1</span>
            </div>
        </div>

        <div class="flex items-center gap-6">
            <div
                class="flex items-center gap-2 bg-red-50 dark:bg-red-900/20 px-3 py-1.5 rounded-lg border border-red-100 dark:border-red-800/50">
                <span class="material-symbols-outlined text-red-500 text-lg">timer</span>
                <span id="timer" class="font-mono font-bold text-red-600 dark:text-red-400 text-lg">00:00</span>
            </div>
            <button id="finish-btn"
                class="px-4 py-2 bg-green-600 hover:bg-green-700 text-white text-sm font-bold rounded-lg transition-colors shadow-sm">
                Finish Test
            </button>
        </div>
    </header>

    <!-- Main Content -->
    <main class="flex-grow pt-24 pb-24 px-4 sm:px-6 lg:px-8 max-w-5xl mx-auto w-full">
        <!-- Progress Bar -->
        <div class="w-full h-1.5 bg-gray-200 dark:bg-gray-700 rounded-full mb-8 overflow-hidden">
            <div id="progress-bar" class="h-full bg-primary transition-all duration-300 w-0"></div>
        </div>

        <!-- Question Container -->
        <div id="question-container" class="space-y-6">
            <!-- Loading State -->
            <div class="animate-pulse space-y-4">
                <div class="h-4 bg-gray-200 dark:bg-gray-700 rounded w-3/4"></div>
                <div class="h-32 bg-gray-200 dark:bg-gray-700 rounded w-full"></div>
            </div>
        </div>
    </main>

    <!-- Footer Navigation -->
    <footer
        class="bg-white dark:bg-[#151e32] border-t border-gray-200 dark:border-gray-700 h-20 fixed bottom-0 left-0 right-0 z-50 px-4 sm:px-8 flex items-center justify-between shadow-[0_-4px_6px_-1px_rgba(0,0,0,0.1)]">
        <button id="prev-btn"
            class="px-6 py-2.5 bg-white dark:bg-gray-800 border-2 border-gray-200 dark:border-gray-600 text-text-main dark:text-gray-300 font-bold rounded-xl hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2">
            <span class="material-symbols-outlined">arrow_back</span> Previous
        </button>

        <div class="flex gap-2">
            <!-- Question indicators generated by JS -->
            <div id="question-dots" class="hidden md:flex gap-1.5 overflow-x-auto max-w-md py-1 px-2"></div>
        </div>

        <button id="next-btn"
            class="px-6 py-2.5 bg-primary hover:bg-primary-hover text-white font-bold rounded-xl transition-colors shadow-lg hover:shadow-primary/30 flex items-center gap-2">
            Next <span class="material-symbols-outlined">arrow_forward</span>
        </button>
    </footer>
</div>

<!-- Raw Data -->
<script>
    const TEST_TYPE = "<?= esc($test_type) ?>";
    const RAW_DATA = <?= json_encode($questions) ?>;
    const SUBMIT_URL = "<?= base_url('ai-tools/mock-submit') ?>";
</script>

<script>
    document.addEventListener('DOMContentLoaded', () => {
        const testData = RAW_DATA;
        const state = {
            currentSectionIndex: 0,
            currentQuestionIndex: 0,
            responses: {}, // { question_id: "answer" }
            startTime: Date.now(),
            timerInterval: null,
            flatQuestions: []
        };

        // Flatten questions for easier navigation
        let totalQ = 0;
        testData.sections.forEach((section, sIdx) => {
            section.questions.forEach((q, qIdx) => {
                state.flatQuestions.push({
                    sectionIndex: sIdx,
                    questionIndex: qIdx,
                    section: section,
                    question: q,
                    globalIndex: totalQ++
                });
            });
        });

        const els = {
            container: document.getElementById('question-container'),
            prevBtn: document.getElementById('prev-btn'),
            nextBtn: document.getElementById('next-btn'),
            finishBtn: document.getElementById('finish-btn'),
            progressBar: document.getElementById('progress-bar'),
            currentSectionNum: document.getElementById('current-section-num'),
            totalSections: document.getElementById('total-sections'),
            timer: document.getElementById('timer'),
            dots: document.getElementById('question-dots')
        };

        els.totalSections.textContent = testData.sections.length;

        // Timer
        state.timerInterval = setInterval(() => {
            const diff = Math.floor((Date.now() - state.startTime) / 1000);
            const m = Math.floor(diff / 60).toString().padStart(2, '0');
            const s = (diff % 60).toString().padStart(2, '0');
            els.timer.textContent = `${m}:${s}`;
        }, 1000);

        function renderQuestion(index) {
            if (index < 0 || index >= state.flatQuestions.length) return;
            state.currentGlobalIndex = index;

            const qData = state.flatQuestions[index];
            const section = qData.section;
            const q = qData.question;

            els.currentSectionNum.textContent = qData.sectionIndex + 1;

            // Progress
            const pct = ((index + 1) / state.flatQuestions.length) * 100;
            els.progressBar.style.width = `${pct}%`;

            // Render
            let html = '';

            // Check if section has a passage
            const hasPassage = section.passage && section.passage.trim().length > 0;

            if (hasPassage) {
                // STACKED VIEW
                html = `
                <div class="flex flex-col gap-8 animate-fade-in max-w-4xl mx-auto">
                    <!-- Passage Panel -->
                    <div class="bg-white dark:bg-card-dark rounded-2xl p-6 md:p-8 border border-gray-200 dark:border-gray-700 shadow-sm">
                        <div class="flex items-center justify-between mb-4 border-b border-gray-100 dark:border-gray-700 pb-2">
                             <span class="text-xs font-bold tracking-wider text-primary uppercase">Passage / Audio Script</span>
                             ${section.name.toLowerCase().includes('listening') ?
                        `<button onclick="playAudio('${encodeURIComponent(section.passage)}')" class="flex items-center gap-2 px-3 py-1.5 bg-primary/10 hover:bg-primary/20 text-primary rounded-lg text-xs font-bold transition-colors">
                                <span class="material-symbols-outlined text-[18px]">volume_up</span> Play Audio
                              </button>` : ''}
                        </div>
                        <div class="prose dark:prose-invert max-w-none text-text-main dark:text-gray-200 text-base leading-relaxed max-h-[400px] overflow-y-auto pr-2 custom-scrollbar">
                            ${section.passage.replace(/\n/g, '<br>')}
                        </div>
                    </div>
                    
                    <!-- Question Panel -->
                    <div class="bg-white dark:bg-card-dark rounded-2xl p-6 md:p-8 border border-gray-200 dark:border-gray-700 shadow-sm">
                         <div class="mb-6 pb-6 border-b border-gray-100 dark:border-gray-700">
                            <span class="text-xs font-bold tracking-wider text-primary uppercase mb-2 block">${section.name} - Q${state.currentGlobalIndex + 1}</span>
                            <h2 class="text-xl font-medium text-text-main dark:text-white leading-relaxed">
                                ${q.prompt.replace(/\n/g, '<br>')}
                            </h2>
                        </div>
                        <div>
                `;
            } else {
                // STANDARD VIEW
                html = `
                <div class="bg-white dark:bg-card-dark rounded-2xl p-8 border border-gray-200 dark:border-gray-700 shadow-sm animate-fade-in max-w-4xl mx-auto">
                    <div class="mb-6 pb-6 border-b border-gray-100 dark:border-gray-700">
                        <span class="text-xs font-bold tracking-wider text-primary uppercase mb-2 block">${section.name}</span>
                        <h2 class="text-xl font-medium text-text-main dark:text-white leading-relaxed">
                            ${q.prompt.replace(/\n/g, '<br>')}
                        </h2>
                    </div>
                    <div>
                `;
            }

            if (q.type === 'mcq') {
                html += `<div class="space-y-3">`;
                q.options.forEach((opt, idx) => {
                    const isChecked = state.responses[index] === String(idx);
                    html += `
                        <label class="flex items-center gap-4 p-4 rounded-xl border-2 cursor-pointer transition-all hover:bg-gray-50 dark:hover:bg-gray-800 ${isChecked ? 'border-primary bg-blue-50/50 dark:bg-blue-900/10' : 'border-gray-200 dark:border-gray-700'}">
                            <input type="radio" name="q_${index}" value="${idx}" class="w-5 h-5 text-primary focus:ring-primary" ${isChecked ? 'checked' : ''} onchange="saveResponse(${index}, '${idx}')">
                            <span class="text-base text-text-main dark:text-white font-medium">${opt}</span>
                        </label>
                    `;
                });
                html += `</div>`;
            } else if (q.type === 'speaking_text') {
                // Speaking UI (Speech-to-Text)
                const val = state.responses[index] || '';
                const isRecording = state.recordingSession === index;

                html += `
                    <div class="space-y-6">
                        <div class="flex flex-col items-center justify-center p-8 bg-gray-50 dark:bg-gray-800/50 rounded-2xl border-2 border-dashed border-gray-300 dark:border-gray-700 transition-colors" id="recording-area-${index}">
                            
                            <!-- Recording Animation/Status -->
                            <div class="relative mb-6">
                                <div id="mic-ring-${index}" class="absolute inset-0 rounded-full bg-red-500/20 scale-150 animate-ping hidden"></div>
                                <button onclick="toggleSpeech(${index})" 
                                    class="relative z-10 w-20 h-20 rounded-full flex items-center justify-center transition-all transform hover:scale-105 shadow-xl ${isRecording ? 'bg-red-500 text-white' : 'bg-primary text-white'}">
                                    <span id="mic-icon-${index}" class="material-symbols-outlined text-[32px]">${isRecording ? 'stop' : 'mic'}</span>
                                </button>
                            </div>

                            <p id="rec-status-${index}" class="text-sm font-bold text-slate-500 dark:text-slate-400 uppercase tracking-widest mb-2">
                                ${isRecording ? 'Listening...' : 'Tap to Speak'}
                            </p>
                            <p class="text-xs text-slate-400 text-center max-w-xs">
                                Click the microphone and answer the question naturally. We will transcribe your speech for analysis.
                            </p>
                        </div>

                        <!-- Transcript Area -->
                        <div class="relative">
                            <label class="absolute -top-3 left-4 bg-white dark:bg-card-dark px-2 text-xs font-bold text-primary">Live Transcript</label>
                            <textarea 
                                id="transcript-${index}"
                                class="w-full h-32 p-4 rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-black/20 text-text-main dark:text-white focus:ring-2 focus:ring-primary focus:border-transparent resize-none overflow-y-auto"
                                placeholder="Your speech will appear here..."
                                readonly
                            >${val}</textarea>
                        </div>
                    </div>
                `;
            } else {
                // Text input (Writing)
                const val = state.responses[index] || '';
                html += `
                    <div>
                        <textarea 
                            class="w-full h-48 p-4 rounded-xl border border-gray-300 dark:border-gray-600 bg-white dark:bg-black/20 text-text-main dark:text-white focus:ring-2 focus:ring-primary focus:border-transparent resize-none font-mono text-sm leading-relaxed"
                            placeholder="Type your response here..."
                            oninput="saveResponse(${index}, this.value)"
                        >${val}</textarea>
                        <p class="mt-2 text-xs text-text-muted text-right">Word count: <span id="word-count-${index}">${val.split(/\s+/).filter(w => w.length > 0).length}</span></p>
                    </div>
                `;
            }

            html += `</div></div>`;
            els.container.innerHTML = html;

            // Update Nav State
            els.prevBtn.disabled = index === 0;
            if (index === state.flatQuestions.length - 1) {
                els.nextBtn.innerHTML = `Complete <span class="material-symbols-outlined">check_circle</span>`;
                els.nextBtn.classList.add('bg-green-600', 'hover:bg-green-700');
                els.nextBtn.classList.remove('bg-primary', 'hover:bg-primary-hover');
                els.nextBtn.onclick = finishTest;
            } else {
                els.nextBtn.innerHTML = `Next <span class="material-symbols-outlined">arrow_forward</span>`;
                els.nextBtn.classList.add('bg-primary', 'hover:bg-primary-hover');
                els.nextBtn.classList.remove('bg-green-600', 'hover:bg-green-700');
                els.nextBtn.onclick = () => renderQuestion(index + 1);
            }
        }

        window.saveResponse = (index, val) => {
            state.responses[index] = val;
            // Update word count if textarea
            const wcEl = document.getElementById(`word-count-${index}`);
            if (wcEl) {
                wcEl.textContent = val.split(/\s+/).filter(w => w.length > 0).length;
            }
        };

        // Speech Recognition Logic
        let recognition = null;
        window.toggleSpeech = (qId) => {
            if (state.recordingSession === qId) {
                // Stop
                if (recognition) recognition.stop();
                state.recordingSession = null;
                renderQuestion(state.currentGlobalIndex); // Re-render to update UI
                return;
            }

            // Start
            if (!('webkitSpeechRecognition' in window) && !('SpeechRecognition' in window)) {
                alert("Your browser does not support speech recognition. Please type your answer.");
                return;
            }

            state.recordingSession = qId;
            const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
            recognition = new SpeechRecognition();
            recognition.continuous = true;
            recognition.interimResults = true;
            recognition.lang = 'en-US';

            recognition.onstart = () => {
                renderQuestion(state.currentGlobalIndex); // to show stop button
            };

            recognition.onresult = (event) => {
                let finalTrans = state.responses[qId] || '';
                let interimTrans = '';

                for (let i = event.resultIndex; i < event.results.length; ++i) {
                    if (event.results[i].isFinal) {
                        finalTrans += event.results[i][0].transcript + ' ';
                    } else {
                        interimTrans += event.results[i][0].transcript;
                    }
                }

                // Update State & UI
                const currentText = finalTrans + interimTrans;
                state.responses[qId] = currentText;  // CAUTION: overwriting or appending? Here simpler to append if we managed final nicely, but for now just replacing with accum
                // Ideally, we should append to existing manually typed text if user mixed modes.
                // But simplified:

                const txt = document.getElementById(`transcript-${qId}`);
                if (txt) txt.value = currentText;
            };

            recognition.onerror = (e) => {
                console.error("Speech Error", e);
                state.recordingSession = null;
                renderQuestion(state.currentGlobalIndex);
            };

            recognition.onend = () => {
                state.recordingSession = null;
                renderQuestion(state.currentGlobalIndex);
            };

            recognition.start();
        };

        // Audio Playback
        window.playAudio = (text) => {
            const decoded = decodeURIComponent(text);
            const utterance = new SpeechSynthesisUtterance(decoded);
            utterance.rate = 0.9; // Slightly slower for clarity
            utterance.pitch = 1;
            window.speechSynthesis.cancel(); // Stop any previous
            window.speechSynthesis.speak(utterance);
        };

        els.prevBtn.onclick = () => renderQuestion(state.currentGlobalIndex - 1);
        els.finishBtn.onclick = finishTest;

        async function finishTest() {
            if (!confirm("Are you sure you want to finish the test?")) return;

            clearInterval(state.timerInterval);

            // Show loading overlay
            const overlay = document.createElement('div');
            overlay.className = 'fixed inset-0 bg-black/50 backdrop-blur-sm z-[100] flex items-center justify-center';
            overlay.innerHTML = `
                <div class="bg-white dark:bg-card-dark p-8 rounded-2xl shadow-2xl flex flex-col items-center max-w-sm text-center">
                    <div class="w-16 h-16 border-4 border-primary border-t-transparent rounded-full animate-spin mb-4"></div>
                    <h3 class="text-xl font-bold text-text-main dark:text-white">Analyzing Results...</h3>
                    <p class="text-text-muted mt-2">AI is grading your responses. This may take a moment.</p>
                </div>
            `;
            document.body.appendChild(overlay);

            try {
                const res = await fetch(SUBMIT_URL, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        test_type: TEST_TYPE,
                        responses: state.responses
                    })
                });

                const json = await res.json();
                if (json.redirect) {
                    window.location.href = json.redirect;
                } else {
                    alert("Error: " + (json.error || "Unknown error"));
                    overlay.remove();
                }
            } catch (e) {
                console.error(e);
                alert("Network error. Please try again.");
                overlay.remove();
            }
        }

        // Init
        if (state.flatQuestions.length > 0) {
            renderQuestion(0);
        } else {
            els.container.innerHTML = `<div class="text-center p-12"><h2 class="text-xl">Error loading test data. Please try again.</h2></div>`;
        }
    });
</script>

<style>
    @keyframes fade-in {
        from {
            opacity: 0;
            transform: translateY(10px);
        }

        to {
            opacity: 1;
            transform: translateY(0);
        }
    }

    .animate-fade-in {
        animation: fade-in 0.3s ease-out forwards;
    }
</style>